### ISSUE TITLE
feature request: tag the thread author in the "Please continue thread here" message

### ISSUE THREAD

**Issue by jordanlewis** [maryliag/cross-post#3]
If we tag the thread author on the "Please continue thread here" message, maybe like "Please continue thread here (original poster: @foo)", then it'll be as quick as possible for that original poster to know to move to the thread. You could also tag all the thread participants, but just the thread author would help I think.

**Comment by maryliag** [comment]
I can get the author for the original message, but to get all the authors from a thread the bot needs to be invite to all channels 😞 
Keeping this issue focused on adding just the original author
